apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: staging
  name: flask-kube-ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-kube-ci
    spec:
      containers:
      - image: registry.gitlab.com/_USER_/flask-kube-ci:staging        
        name: flask-kube-ci
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: gitlab-registry